arkhn/fhir-river

fhir_extractor/src/app.py, fhir_transformer/requirements.txt, fhir_transformer/src/analyze/cleaning_script.py, fhir_transformer/src/analyze/concept_map.py, fhir_transformer/src/analyze/merging_script.py, fhir_transformer/src/main.py, fhir_transformer/src/transform/dataframe.py, fhir_transformer/src/transform/fhir.py, fhir_transformer/src/transform/transformer.py
This improves performances and removes one dependency.
=> Manually transform data instead of using pandas

fhir_transformer/src/analyze/analyzer.py
https://github.com/arkhn/fhir-river/issues/26
=> Issue 26 refresh mapping analyser transform

.github/workflows/main.yml, .gitignore, README.md, analyzer/src/analyze/analyzer.py, analyzer/src/analyze/graphql.py, analyzer/src/analyze/mapping.py, analyzer/test/analyze/test_analyzer.py, analyzer/test/analyze/test_graphql.py, api/src/app.py, docker-compose.yml, extractor/src/extract/extractor.py, extractor/src/main.py, loader/src/main.py, test/consumer_class.py, test/docker-compose.yml, test/test_batch.py, transformer/src/main.py
=> Use identifiers instead of token to login to pyrog

.github/workflows/main.yml, README.md, api/Dockerfile, api/entrypoint.sh, api/requirements.txt, api/src/app.py, api/uwsgi.ini, docker-compose.yml, test/docker-compose.yml, test/test_batch.py, transformer/uwsgi.ini
I improved the CI in order to cache docker images for each build. The workflow gets a bit complicated; maybe we'll have to factor it at some point
=> Publish docker images and update ports

analyzer/src/analyze/analyzer.py, transformer/src/main.py
Refresh analysis in transformer when using its api
=> Force refresh transformer's analysis on preview

apigo/api/preview.go
Notably solves https://github.com/arkhn/pyrog/issues/336
=> Convey extractor and transformer errors on preview

extractor/src/errors.py, extractor/src/extract/extractor.py
To avoid useless KeyError messages
=> Raise custom error when column not found in table

analyzer/src/analyze/sql_column.py, analyzer/test/analyze/test_sql_column.py
=> Fix column name hashing (#86)

extractor/requirements.txt, extractor/src/json_encoder.py, extractor/src/main.py
Also add forgotten dependency to pyodbc in requirements.txt
=> Override flask's JSONEncoder to serialize decimal values

docker-compose.yml, loader/src/cache/__init__.py, loader/src/main.py
* Fix mongo warning on calling mongo client before fork
=> fix: call mongo client before fork

loader/src/main.py, logger/logger.py, test/docker-compose.yml, test/test_batch.py, test/test_loader_reference_binder.py, test/volumes/mapping.json, transformer/src/main.py
Fix integration tests by removing authentication flows during them.
=> Skip authentication during integration tests

analyzer/src/analyze/condition.py, analyzer/test/analyze/test_analyzer.py, analyzer/test/analyze/test_condition.py, analyzer/test/fixtures/patient_mapping.json, api/src/producer_class.py, extractor/src/main.py, extractor/src/producer_class.py, loader/src/main.py, loader/src/producer_class.py, logger/__init__.py, logger/logger.py, transformer/src/main.py, transformer/src/producer_class.py, transformer/src/transform/fhir.py, transformer/src/transform/transformer.py, transformer/test/transform/test_fhir.py
Fixes #132  by @elsiehoffet-94 
Fix broken edge cases with conditions
=> Fix conditions

extractor/src/json_encoder.py, extractor/src/producer_class.py
The trailing ".0" were only fixed for previews in #127
=> Use custom JSON encoder for kafka events in extractor

.github/workflows/main.yml
Disable e2e tests until they can be brought back confidently.
Related to #141
=> Disable e2e tests

extractor/src/extract/extractor.py, extractor/test/extract/test_extractor.py
=> [extractor] Use = instead of IN in filter query with single values

extractor/src/extract/extractor.py, extractor/test/extract/test_extractor.py
Fixes https://github.com/arkhn/pyrog/issues/232
Parse between filter value as a comma separated string and use sqlalchemy to filter with it.
=> Handle between filter

transformer/src/transform/dataframe.py, transformer/src/transform/fhir.py, transformer/src/transform/transformer.py, transformer/test/transform/test_dataframe.py, transformer/test/transform/test_fhir.py
When handling lists without joins, only the first items was considered
=> Fix bug when handling lists in Transformer

transformer/requirements-tests.txt, transformer/src/transform/dataframe.py, transformer/test/conftest.py, transformer/test/transform/test_dataframe.py
Fixes #150 
Apply cleaning scripts before casting to right type
Not tested yet, will try on dev
=> Apply cleaning scripts before casting to right type

extractor/requirements/requirements-base.txt, loader/requirements.txt, requirements-dev.txt, transformer/requirements.txt
=> Bump cleaning scripts requirements

analyzer/src/analyze/sql_column.py, analyzer/test/analyze/test_analyzer.py, extractor/src/extract/query_builder.py, extractor/test/extract/test_query_builder.py
Fix some stuff with conditions and query builder
Will test on dev with integration tests
=> Disable joins on conditions

CHANGELOG.md
I wanted to release a new version of river after the 2 current PRs (#166 and #167) are merged.
So here is the changelog to keep track of what has happened since last release.
🚧 I want the other PRs to be merged before this one 🚧
=> Add a CHANGELOG.md to the repo

transformer/src/transform/fhir.py, transformer/test/transform/test_fhir.py
There was a bug when transforming arrays of literals.
Tested on dev and added a unit test.
=> Fix transformation of literal arrays

extractor/requirements/requirements-base.txt, loader/requirements.txt, requirements-dev.txt, transformer/requirements.txt
Bump CS requirements to 0.2.27
=> Bump requirements for cleaning scripts 

extractor/src/extract/extractor.py, extractor/src/extract/query_builder.py, extractor/src/main.py, extractor/test/extract/test_query_builder.py
Fixes bug with duplicated joins
Fixes bug with duplicated joins
Fixes bug with duplicated joins
Unit test
=> Avoid duplicated joins

.github/workflows/integration.yml
The workflow with `workflow_run` needs to be on the default branch
=> Add integration workflow

analyzer/src/analyze/condition.py, analyzer/test/analyze/test_condition.py, analyzer/test/analyze/test_input_groups.py
=> Fix Condition.check

.github/workflows/main.yml, api/Dockerfile, api/main.go, api/mapping/fetch.go, api/mapping/mapping_test.go, api/mocks/fhir_api.go, api/mocks/patient_mapping.go, api/mocks/pyrog_server.go, api/monitor/create_topics.go, api/monitor/destroy.go, api/monitor/listen_and_destroy.go, api/monitor/save_resources_list.go, api/monitor/types.go, api/routes/batch/create.go, api/routes/preview/preview_test.go, api/topics/constants.go, extractor/requirements/requirements-base.txt, extractor/src/consumer_class.py, extractor/src/extract/extractor.py, extractor/src/extract/query_builder.py, extractor/src/main.py, extractor/src/producer_class.py, loader/requirements.txt, loader/src/consumer_class.py, loader/src/main.py, loader/src/producer_class.py, transformer/requirements.txt, transformer/src/consumer_class.py, transformer/src/main.py, transformer/src/producer_class.py
Fixes #85  by @simonvadee 
Fixes #24  by @maxenceh  
* When a batch is launched, topics `batch.{batch_id}`, `extract.{batch_id}`, `transform.{batch_id}`, `load.{batch_id}` are created and its list of resource ids (a set of key `batch:{batch_id}:resources`) recorded in Redis.
* At runtime, a counter for each batch is created. This counter is a hash of key "batch:{batch_id}:counter". It contains elements of keys `resource:{resource_id}:extracted` and `resource:{resource_id}:loaded` which refers to the numbers of extracted records and loaded resources respectively for a resource id.
* In River API, a thread consumes load.* topics to follow batch advancements according to the batch counters in Redis. When a batch ends, batch topics and Redis keys are deleted/expired.
* A new route …
=> Feat: implement batch cancellation

api/main.go
Allow delete requests in CORS settings
=> fix: add delete to API allowed methods to fix cors error

loader/src/reference_binder.py, loader/test/conftest.py, loader/test/test_reference_binder.py
=> Handle the case where identifier has cardinality 0..1

.github/workflows/main.yml, .gitignore, api/main.go, api/routes/batch/create.go, api/routes/batch/list.go, api/topics/delete.go, api/topics/monitor/cache_batch_info.go, api/topics/monitor/destroy.go, api/topics/monitor/retrieve_batch_list.go, api/topics/monitor/save_resources_list.go
* Add `/batch GET` route
Integration test
=> feat: add a route to retrieve a batch list

.github/workflows/main.yml, analyzer/src/analyze/analyzer.py, analyzer/src/analyze/condition.py, analyzer/src/analyze/input_group.py, analyzer/src/analyze/sql_column.py, analyzer/src/analyze/sql_filter.py, analyzer/test/analyze/test_analyzer.py, analyzer/test/fixtures/patient_mapping.json, api/mapping/fetch.go, api/mapping/types.go, extractor/src/extract/query_builder.py, extractor/test/extract/test_query_builder.py
Fixes #169
Use joins in conditions and filters to build the sql query.
None yet
=> Process joins on conditions and filters

django/extractor/management/commands/extractor.py, django/loader/management/commands/loader.py, django/river/settings/base.py, django/transformer/management/commands/transformer.py, django/utils/exporter.py, monitoring/README.md, monitoring/grafana/dashboards/river.json, monitoring/grafana/provisioning/dashboards/all.yml, monitoring/grafana/provisioning/datasources/prometheus.yml, monitoring/prometheus.yml
Custom metrics were disabled with the refactoring.
Start exporter with services
=> Bring back custom metrics

django/transformer/transform/dataframe.py, django/transformer/transform/fhir.py, tests/transformer/transform/test_dataframe.py, tests/transformer/transform/test_fhir.py, tests/transformer/transform/test_transform.py
Only the first letter of the input was used in array of literal static values
Fixes https://github.com/arkhn/pyrog/issues/485
=> Fix list of static values literals

django/loader/reference_binder.py, django/transformer/transform/fhir.py, tests/transformer/transform/test_fhir.py
=> Fix transformation of documents with nested arrays

django/common/analyzer/analysis.py, django/common/analyzer/analyzer.py, django/loader/reference_binder.py, tests/analyzer/fixtures/patient_mapping.json, tests/analyzer/test_analyzer.py, tests/loader/conftest.py, tests/loader/test_reference_binder.py
=> Fix reference binding of arrays of references

django/extractor/extract/query_builder.py, tests/extractor/extract/test_query_builder.py
=> Fix multi hop joins

pyproject.toml, requirements/tests.txt, tests/pyrog/migrations/conftest.py, tests/pyrog/migrations/test_0002_unique_source_name.py
Add test for #255, but had to come after #261
=> Test pyrog migration

.github/workflows/main.yml
=> ci: remove testy version

django/pyrog/api/filters.py, django/pyrog/api/views.py, django/river/settings/base.py, pyrog-schema.yml, requirements/base.txt, tests/pyrog/api/test_attribute.py, tests/pyrog/api/test_resource.py
=> Source filters on resource and attribute

django/pagai/database_explorer/database_explorer.py
=> [pagai] Fix typo in DB explorer

django/transformer/transform/fhir.py, tests/transformer/transform/test_fhir.py, tests/transformer/transform/test_transform.py
Sometimes, conditions are here to filter out all values except one so that we can fill a non-list attribute.
=> Handle case where conditions are here to filter out all rows except one in non-list attribute

.github/workflows/django.yml, django/river/settings/prod.py
#253 forces users to be authenticated. Too early to that.
Allow any in prod (as before).
=> Lessen permissions checks

.github/workflows/django.yml
This reverts commit 582429c4247ab056138cb2a7150e7c818ea800d7.
=> Revert debug

requirements/base.txt, requirements/dev.txt
Bump several deps (including django as suggested by dependabot)
=> chore: upgrade dependencies

django/common/analyzer/condition.py, tests/analyzer/test_condition.py
Quick addition for urgent need
Did I miss something?
Goes with https://github.com/arkhn/pyrog/pull/507
=> Add IN relation to conditions

django/common/analyzer/condition.py, django/common/analyzer/sql_column.py, django/transformer/transform/dataframe.py, tests/analyzer/test_condition.py, tests/control/test_api.py, tests/transformer/transform/test_dataframe.py, tests/transformer/transform/test_transform.py
The loop on rows was not performed correctly when the attribute was only composed of static inputs
=> Fix condition arrays on static inputs

django/pyrog/models.py, tests/pyrog/api/__snapshots__/test_source.ambr, tests/pyrog/api/test_resource.py, tests/pyrog/factories.py
=> feat(api): auto-generate logical ref

django/pyrog/api/views.py, pyrog-schema.yml, tests/pyrog/api/test_filter.py
Add filter and update openapi schema
=> feat(api): filter filters by resource

.github/workflows/main.yml, docker-entrypoint.sh
Remove deprecated line to allow static files collection
=> fix: collectstatic

docker-entrypoint.sh
Running migrations should be intentional
=> chore(docker): no auto migrate in prod

app/src/features/Mappings/Delete/MappingDeleteDialog.tsx, app/src/features/Mappings/Edit/MappingNameDialog.tsx
=> fix(app): bad import

app/src/features/Mappings/Delete/MappingDeleteDialog.tsx, app/src/features/Mappings/Edit/MappingNameDialog.tsx, django/pyrog/urls.py
=> fix(api): fhir proxy route pattern

app/src/services/api/endpoints.ts, django/river/settings/dev.py
* Rollback django dev settings to make oidc logout work. 
* Change in `endpoints.ts`
=> fix: oidc logout

app/src/services/api/cache.ts, app/src/services/api/endpoints.ts, django/river/settings/dev.py, docker-compose.yml
=> chore: docker compose env var default values

app/src/app/routes/Router.tsx
=> fix(app): enable browser router basename

app/src/common/hooks/useFhirResourceTreeData.ts, app/src/features/FhirResourceTree/FhirResourceTree.tsx, app/src/features/FhirResourceTree/resourceTreeSlice.ts
=> refactor(app): tree builder algorithm

app/src/services/api/apiBaseQuery.ts
https://timonweb.com/django/how-to-make-django-requestis_ajax-work-with-js-fetch/
=> fix(app): add x-requested-with header

django/control/api/views.py, django/extractor/extract/extractor.py, django/extractor/service.py
We've remarked that connection opened by the Extractor were never closed
=> Pass session and metadata to Extractor instead of DBConnection

django/common/kafka/producer.py, requirements/base.txt
=> Use chardet to find bytes encoding

app/src/services/api/generated/api.generated.ts, django/pyrog/api/filters.py, django/pyrog/api/views.py, river-schema.yml, tests/pyrog/api/test_condition.py, tests/pyrog/api/test_input.py, tests/pyrog/api/test_input_group.py
Added several filters for django resources : 
- InputGroups : 
- Attribute filter
- Inputs :  
- InputGroup filter
- Conditions :
- InputGroup filter
=> Added filters for InputGroups, Inputs & Conditions

CONTRIBUTING.md, README.md, TROUBLESHOOTING.md
=> doc: add troubleshooting

app/src/app/App.tsx, app/src/app/routes/AppBar.tsx, app/src/app/usePyrogTheme.ts, app/src/common/components/IconButton.tsx, app/src/common/hooks/usePyrogTheme.ts, app/src/common/test/test-utils.tsx, app/src/features/Columns/ColumnSelect.tsx, app/src/features/FhirAttributePanel/Condition.tsx, app/src/features/FhirAttributePanel/SqlInput.tsx, app/src/features/FhirAttributePanel/StaticInput.tsx, app/src/features/FhirResourceTree/FhirResourceTree.tsx, app/src/features/FhirResourceTree/TreeItem.tsx, app/src/features/FhirResourceTree/TreeItemLabel.tsx, app/src/features/FhirResourceTree/TreeNodeBadge.tsx, app/src/features/Mappings/Create/FhirProfileStep.tsx, app/src/features/Mappings/Create/FhirResourceStep.tsx, app/src/features/Mappings/Create/TableStep.tsx, app/src/features/Mappings/MappingInfo.tsx
Add a theme hook to edit the theme as we want, and remove all hard coded colors.
=> add a hook for using theme and remove all hard coded colors

app/src/services/api/generated/api.generated.ts, django/pyrog/api/serializers/import_export.py, django/pyrog/api/views.py, django/settings/base.py, river-schema.yml, tests/pyrog/api/serializers/test_import_export.py
Replace the Source `full` query parameter by extra actions https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing in order to generate dedicated endpoints for mapping import/export
=> feat(api): generate openapi mapping import export endpoints

django/river/adapters/mappings.py, django/river/adapters/progression_counter.py, tests/river/conftest.py, tests/river/e2e/api/test_batch.py, tests/river/integration/adapters/test_mappings_repo.py
Some tests weren't really testing what happens
=> Improve tests

django/river/common/analyzer/analyzer.py, django/river/extractor/service.py, django/river/transformer/service.py, tests/river/unit/analyzer/test_analyzer.py
For each Extractor -> Transformer event, we were fetching the mapping in redis which wasn't what we want
=> Cache analysis in memory in Transformer

app/src/services/api/generated/api.generated.ts, django/pyrog/api/serializers/import_export.py, river-schema.yml
When importing a mapping, the response must contain the new source id
=> feat(mapping): add new source id to import mapping response

django/pyrog/api/views.py, requirements/tests.txt, tests/pyrog/api/test_attribute.py, tests/pyrog/api/test_column.py, tests/pyrog/api/test_credential.py, tests/pyrog/api/test_input.py, tests/pyrog/api/test_input_group.py, tests/pyrog/api/test_join.py, tests/pyrog/api/test_resource.py, tests/pyrog/api/test_source.py
The ui lists the objects by creation date and it should be the default ordering
=> feat(api): order objects by creation date

django/common/scripts/cleaning/map_priority.py, tests/common/scripts/cleaning/test_map_priority.py
Where is the place to increment the version number ? 
PR from
https://github.com/arkhn/cleaning-scripts/pull/61
=> fix(map_priority) : priority starts from 1 and not from 0

django/pyrog/api/serializers/basic.py, docker-compose.test.yml, tests/pyrog/api/test_credential.py, tests/pyrog/api/test_owner.py
=> Fix CredentialSerializer.get_available_owners

django/common/scripts/cleaning/clean_instant.py, django/common/scripts/merging/__init__.py, django/common/scripts/merging/merge_instant.py, tests/common/scripts/merging/test_merge_instant.py
Merge date and time into instant datatype
=> feat(merge_instant): add merge_instant script

CONTRIBUTING.md, django/core/management/commands/docs.py, requirements/dev.txt
Fixes #458 
This is only the first step of serving documentation, the next step is to serve these files directly through nginx in order for it to be accessible on dev/staging/demo etc...
=> feat: add docs command to django CLI

django/pyrog/api/serializers/import_export.py, tests/pyrog/api/test_source.py
=> fix: multiple imports of a mapping

django/river/adapters/progression_counter.py, django/river/topicleaner/service.py, docker-compose.test.yml, hapi-loader/src/main/java/com/arkhn/hapi/loader/FhirServerConfigR4.java, hapi-loader/src/main/java/com/arkhn/hapi/loader/ResourceConsumer.java, tests/river/conftest.py, tests/river/factories.py, tests/river/fixtures/mimic_mapping.json, tests/river/integration/adapters/test_progression_counter.py, tests/river/unit/extractor/test_handler.py, tests/river/unit/test_services.py, tests/river/unit/topicleaner/test_service.py, tests/river/unit/transformer/test_handler.py
=> ProgressionCounter: add failures counter 

django/river/migrations/0002_batch_mappings.py, django/river/models.py
=> fix(migrate): add null=True for migration

app/package.json
Fixes #[issue number] by @[issue author]
=> fix(app): app homepage

django/common/scripts/cleaning/__init__.py, django/common/scripts/cleaning/clean_epoch_datetime.py, tests/common/scripts/cleaning/test_clean_epoch_dateTime.py
Convert epoch to datetime. I created a second script because YYYYMMDD and epoch can be ambiguous.
Sorry for the forgotten formatted commit message 🙈
=> Cleaning script: convert epoch to datetime

django/river/api/serializers/serializers.py, river-schema.yml
Asked here https://github.com/arkhn/fhir-river/issues/654#issuecomment-936525351
~~@BPierrick can you check whether the enum is correct from what you receive from the api ? I've looked into hapi code but I don't know if the first letters are uppercase or not for instance.~~
-> https://www.hl7.org/fhir/valueset-issue-severity.html
=> feat(api): operation outcome severity as enum

.template.env, django/pyrog/api/views.py, django/settings/base.py
The fhir proxy needs nginx basic auth credentials to send requests
=> feat(api): add fhir api auth token

app/src/features/Sources/CredentialOwnersSelect.tsx, app/src/locales/en.json, app/src/services/api/endpoints.ts
Fixes https://github.com/orgs/arkhn/projects/7#card-68352672 by @nriss 
Refresh owners schemas on demand
@MiskoG @BPierrick maybe some work has to be done on the design
Tested locally on the river db.
=> feat(app): refresh schemas button

Makefile, django/common/adapters/fhir_api.py, django/pyrog/api/serializers/basic.py, docker-compose.yml, tests/common/adapters/test_fhir_api.py
=> [api] Add FHIR_API_AUTH_TOKEN in docker-compose

hapi-loader/src/main/java/com/arkhn/hapi/loader/ResourceConsumer.java
Fixes https://github.com/arkhn/deployment/issues/527
=> Revert "clean(hapi): remove unused counters"

app/src/features/Preview/Preview.tsx, django/settings/base.py, django/utils/exception_handler.py
- Fixes #720 
- Catches all unhandled exceptions and serves them with exception value.
=> Catch django server errors
