arkhn/fhir-river

- .gitignore
- README.md
- docker-compose.yml
- fhir_extractor/Dockerfile
- fhir_extractor/entrypoint.sh
- fhir_extractor/requirements.txt
- fhir_extractor/src/consumer_class.py
- fhir_extractor/src/errors.py
- fhir_extractor/src/main.py
- fhir_extractor/src/producer_class.py
- fhir_extractor/uwsgi.ini
- fhir_river_api/Dockerfile
- fhir_river_api/requirements.txt
- fhir_river_api/src/app.py
- fhir_river_api/src/config/logger.py
- fhir_transformer/Dockerfile
- fhir_transformer/entrypoint.sh
- fhir_transformer/requirements.txt
- fhir_transformer/src/fhirstore.py
- fhir_transformer/src/main.py
- fhir_transformer/uwsgi.ini
I added a Flask API on fhir_extractor (POST /extract) and fhir_transformer (POST /transform) in order to implement a sync version of the "fhir preview".
You can now send a:
```
curl -X POST http://localhost:5000/preview -d '{"resource_id": "<id of the resource>", "primary_key_values": ["<primary key value>"]}' -H "Content-Type:application/json"
```
and retrieve the transformed fhir object
I used the @postfork and @thread decorators of uwsgi (we now run the transformer and the extractor with uwsgi, it's like gunicorn) in order to spawn a consumer automatically when the api starts.
> Implement synchronized preview

- extractor/requirements.txt
- loader/requirements.txt
- transformer/requirements.txt
Without them, docker compose will use the cached version instead of using the most recent one
Maybe there could be another option by forcing to rebuild the image (I didn't find any except for removing totally the image and repulling it, not sure we want to do that) but at least we have more control if something wrong happens.
> Add cleaning-scripts versions

- .github/workflows/main.yml
- apigo/api/preview.go
- apigo/api/preview_test.go
- apigo/go.mod
- test/test_batch.py
> river-api's preview accepts []string and []int as primary_key_values

- loader/src/reference_binder.py
- loader/test/conftest.py
- loader/test/test_reference_binder.py
We misunderstood how identifiers are built: they always have a value and the "referential" can be indicated whether with system or with both type.coding.system and type.coding.code
If they have both, the system is used but we should allow it
> Fix how identifiers are used in references

- extractor/src/json_encoder.py
- extractor/test/test_json_encoder.py
Fixes ##126 by @elsiehoffet-94 
If an extracted number actually represents an int, then we force the string serialization to represent an integer.
Maybe this would need some further thinking, can we find a better solution?
> Serialize decimal to int string if needed

- .github/workflows/extractor.oracle.yml
- we were logging in to the wrong docker registry
- the image name was missing the docker registry prefix
> [ci] fix publishing private images to mammouth

- analyzer/src/analyze/attribute.py
- analyzer/test/analyze/test_attribute.py
- Return original if fails to cast type
- Add a type attribute for error message
- Change logging level to warning
Fixes #155
> Return raw value on Attribute.cast_type error

- loader/src/load/loader.py
Do you think the document (and maybe the diagnostics?) should even be given as log fields?
> Reformat failed validation error message

- extractor/src/extract/extractor.py
Fixes #147 by @simonvadee 
Use yield_per to avoid loading all the query response in memory
Tested in a toy python script. Maybe we should try to test that in a dev environment.
> Chunk Extractor query responses

- analyzer/src/analyze/attribute.py
- analyzer/test/analyze/test_attribute.py
Sometimes, Decimal were cast to strings with scientific notation. We want to avoid that (at least most the time?)
Unit tests
> Avoid scientific notation when casting to string

- transformer/src/transform/fhir.py
- transformer/src/transform/transformer.py
- transformer/test/transform/test_fhir.py
Remove `clean_fhir_object` which was introduced as an ugly fix for shaky `group_by`s.
Tested on dev, mapping with joins don't have any duplicated array elements.
> [clean] Remove unneeded function

- extractor/src/extract/query_builder.py
- extractor/test/extract/test_query_builder.py
When the same column was written several times in the query, the resulting dataframe was of the form
```
{"duplicated_column": [col_val, col_val, ...]}
```
which causes problems when we try to transform it.
- Unit tests
- Hermès AKA le bac à sable
> Avoid duplicated column in the query

- api/topics/monitor/listen_and_destroy.go
* If the api can't connect to Kafka at launch, it should crash and restart
> fix: replace panic by fatal to exit

- api/go.mod
- api/go.sum
- api/mapping/fetch.go
- api/mapping/mapping_test.go
- api/mocks/pyrog_server.go
- api/routes/preview/preview_test.go
- extractor/requirements/requirements-base.txt
- extractor/src/main.py
- extractor/src/producer_class.py
- loader/src/producer_class.py
- transformer/src/producer_class.py
* If a database error occurs, the extractor should set the number of previously produced messages in the Redis counter in order to terminate the batch.
* Fix Kafka performance issues after bumping to v1.5.0 of Kafka confluent python (wrapper of librdkafka). https://github.com/edenhill/librdkafka/releases/tag/v1.5.0
```
The default producer batch accumulation time, linger.ms, has been changed
from 0.5ms to 5ms to improve batch sizes and throughput while reducing
the per-message protocol overhead.
Applications that require lower produce latency than 5ms will need to
manually set linger.ms to a lower value.
```
> fix: kafka perfomance and set redis counter even if an exception is raised

- extractor/Dockerfile
- extractor/requirements/requirements-base.txt
We had to modify the base docker image to include a workaround for this issue https://github.com/microsoft/msphpsql/issues/1021 (bug in mssql driver with openssl)
> Bump arkhn/python-db-drivers to 0.2.0

- transformer/src/transform/fhir.py
Sometimes, empty leaves (with "" for instance) were still added to the fhir document.
One check wasn't done exactly at the right place.
Tested on a deployed stack.
> Fix handling of empty leaves

- .vscode/settings.json
- django/river/settings/test.py
- pyproject.toml
- requirements/tests.txt
- tests/conftest.py
* uses `pytest-dotenv` to load the `.env` before `pytest-django` calls `django.setup()`
* prevents potential issues when 2 test modules share the same name, by making tests folders package
This PR allows to use the pytest runner from vscode and hence allows usage of the vscode debugger interface.
* https://docs.pytest.org/en/stable/goodpractices.html
* https://docs.pytest.org/en/stable/pythonpath.html
> Support vscode test runner

- Dockerfile
When running apt-get upgrade, we may upgrade the msodbcsql17 package which requires accepting the terms and conditions. ACCEPT_EULA=Y resolves this.
> [docker] automatically accept mssql upgrade terms

- .dockerignore
- hapi-loader/src/main/java/com/arkhn/hapi/loader/KafkaConsumerConfig.java
Default is `latest`, which makes the consumer miss the first events
> Set loader consumer AUTO_OFFSET_RESET_CONFIG to earliest

- django/river/settings/base.py
When working behind a proxy, cookies are shared by the services available through that proxy.
Cookies with the same name will be overridden (e.g. session, csrf cookies), which is problematic.
The way to to deal with that is either to use different DNS entry for the each services (straightforward in SaaS context) or simply to namespace cookies.
* Prefix cookie names with `pyrog_` by default, but allow to be overridden through env
* Should logout users when rolling out this change
> chore: namespace cookies

- Dockerfile
- django/river/settings/base.py
- django/river/settings/prod.py
- docker-entrypoint.sh
- uwsgi.ini
In prod, allow to tell upstream (i.e. pyrog-api) that it is been served behind a proxy under a subpath
> chore: enable uwsgi socket in prod

- django/river/settings/base.py
1 unit test ko bc
Sentry was enabled when it should not  be
> fix(tests): properly parse *_ENABLED variables

- django/common/kafka/producer.py
- django/control/api/views.py
- tests/common/test_json_encoder.py
Pain point: the cleaning scripts has to look like `v.encode("utf-8").decode(...)`
Other solution I can see: augment the mapping with a encoding for byte values
> Fix bytes serde

- django/pyrog/api/views.py
This PR disables caching for every request to hapi fhir (by default, search results are cached for one minute in Hapi)
https://hapifhir.io/hapi-fhir/docs/server_jpa/configuration.html#search-result-caching
> feat(api): no cache for fhir requests

- .github/workflows/main.yml
To gain a precious few minutes, we want to use the testy-action image from the hub.
[cf doc](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses)
> feat(ci): use testy-action from docker-hub

- app/.env.development
- app/Dockerfile
- app/docker-entrypoint.sh
- app/package.json
- app/public/index.html
- app/src/app/routes/Router.tsx
- app/src/constants.ts
- app/src/serviceWorker.ts
- app/src/services/api/apiBaseQuery.ts
- app/src/services/api/urls.ts
- app/src/services/oidc/urls.ts
this is a proposal for front-end packaging. Our goals are:
- have a single image/built app for multiple target environments (= being able to configure URL through env vars)
- stop building the app when starting the container
- have a smooth development workflow (the same as we currently have)
- avoid a complex setup (eg: splitting the logic between `deployment` and the front-end code)
I'm not sure this proposal fulfills all prerequisites (I find it a bit complex and error-prone) but I'd like to have your opinions)
thanks!
> feat(app): template index.html using env variables

- .vscode/settings.json
Vscode has switched the default python language server to pylance, which has typechecking disable by default.
Enable typechecking
> chore(vscode): enable python typechecking (again)

- tests/pagai/test_explore_multi_db.py
Add cdc to unit tests microsoft sql owner, that was causing unit tests fains
> fix(test): add cdc owner to mssql unit tests

- django/common/analyzer/attribute.py
- django/common/normalizers/__init__.py
- django/common/normalizers/normalizers.py
- django/transformer/transform/transformer.py
- tests/transformer/transform/test_transform.py
We did not apply string normalization when computing fhir object IDs, which led to errors with reference binding...
Not sure about the `raise` statement in the normalizer, let me know what you think (and what you'd have done instead)
> fix(transformer): handle decmals when computing fhir objects ID

- django/settings/base.py
`strtobool` returns an integer
> hotfix(settings): bool values from env

- app/src/services/api/generated/api.generated.ts
- django/pyrog/api/views.py
- django/river/api/serializers.py
- django/river/api/views.py
- river-schema.yml
The openapi generation failed on the scripts endpoint because of missing serializer class
> fix(scripts): add a serializer to scripts endpoint view

- django/river/common/database_connection/db_connection.py
- tests/river/unit/common/test_db_connection.py
Fixes #499 by @nriss 
Pyrog need to handle this as well and a model migration is needed (or we could just use the `database` attribute in `credential` prefixing it with something specifying it's a service or a database name)
> feat(river): handle oracle service name

- .github/workflows/main.yml
- django/river/extractor/service.py
- django/river/management/commands/extractor.py
- django/river/management/commands/topicleaner.py
- django/river/management/commands/transformer.py
- django/river/topicleaner/service.py
- django/river/transformer/service.py
The issue was: when importing the module river.extractor.service, the default arguments were instanciated leading to connection issues to kafka/redis etc...
> refactor(river): no default values for adapters
